### ISSUE TITLE
Error when trying to access another plugin's service

### ISSUE THREAD

**Issue by davist11** [pixelandtonic/AppleNews#2]
I have a plugin to generate a YouTube/Vimeo video URL based on the web URL of the video, and I am trying to access it inside `MyNewsArticle.php`.

```
$videoUrl = craft()->videoEmbed->getEmbedUrl($block->videoUrl);
```

I got the error `Call to undefined function craft()` and noticed that this file isn't using the Craft namespace. What is the best way for me to access other plugins' services?

**Comment by takobell** [comment]
This should do it:

    $videoUrl = \Craft\craft()->videoEmbed->getEmbedUrl($block->videoUrl);

**Comment by davist11** [comment]
Perfect, thanks Brad!
