### ISSUE TITLE
Unable to publish to Apple News

### ISSUE THREAD

**Issue by whoisgina** [pixelandtonic/AppleNews#3]
I'm unable to publish articles to Apple News. My API keys and secret are correct, as I am able to view correctly-named sections set within News Publisher in the CP. I'm not able to see the Apple News pane on the right side of entries while editing, but the option to publish is visible in the gear menu on the entries index. However, this option is available for all entries, not just the ones specified in the channel class.

I'm using the included example templates, `MyNewsArticle.php`and `MyNewsChannel.php`, both tailored to fit my section/entry handles and news entry matrix structure where necessary. 

Maybe relevant: when I follow the link from inside the plugin, I get a `{"errors":[{"code":"UNAUTHORIZED"}]}` response.

**Comment by brandonkelly** [comment]
> I'm not able to see the Apple News pane on the right side of entries while editing

Even for entries that are already live?

If the Apple News pane isn't even showing up, then there’s something wrong with your AppleNewsChannel class’s `matchEntry()` function. Maybe the section handle is incorrect?

**Comment by whoisgina** [comment]
Aha! The section handles were correct, but the check for locale was tripping it up. 
```
if ($entry->locale != 'en') {
return false;
}
```

My locale is set to `en_us`. I changed the value in that if statement to `en_us` and now it is working more or less as expected. Thank you!

**Comment by brandonkelly** [comment]
Glad you got it sorted!
