### ISSUE TITLE
Task Error

### ISSUE THREAD

**Issue by bymayo** [pixelandtonic/AppleNews#4]
I'm getting the following error in the logs because all Apple News tasks are failing. 

Any ideas what could be causing this? I can download the content from the articles in the task and preview it in the News Preview app (Just to double check there were no errors with the way the article was formatted)

```
2017/11/22 10:14:47 [error] [application] Encountered an error running task 63856 (AppleNews_PostQueuedArticles), step 1 of 4: Array
(
    [code] => 404
    [message] => HTTP/1.1 404 Not Found
    [response] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => NOT_FOUND
                            [keyPath] => Array
                                (
                                    [0] => articleId
                                )

                            [value] => 206516d9-4401-4b23-8338-5e5e8cf637fa
                        )

                )

        )

)
 in /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197 on line 289 of /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php
```

**Comment by brandonkelly** [comment]
Is there a stack trace associated with the error in your logs?

**Comment by bymayo** [comment]
This is the full output of the log for this error:

> 2017/11/29 10:08:50 [info] [application] [Forced] Starting task AppleNews_PostQueuedArticles that has a total of 23 steps.
> 2017/11/29 10:08:50 [info] [application] [Forced] Starting step 1 of 23 total steps.
> 2017/11/29 10:08:51 [error] [php] Array
> (
>     [code] => 404
>     [message] => HTTP/1.1 404 Not Found
>     [response] => stdClass Object
>         (
>             [errors] => Array
>                 (
>                     [0] => stdClass Object
>                         (
>                             [code] => NOT_FOUND
>                             [keyPath] => Array
>                                 (
>                                     [0] => articleId
>                                 )
> 
>                             [value] => 206516d9-4401-4b23-8338-5e5e8cf637fa
>                         )
> 
>                 )
> 
>         )
> 
> )
>  in /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197 (/home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php:289)
> Stack trace:
> #0 /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php(197): ChapterThree\AppleNewsAPI\PublisherAPI->triggerError()
> #1 /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(104): ChapterThree\AppleNewsAPI\PublisherAPI->onErrorResponse()
> #2 /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(88): ChapterThree\AppleNewsAPI\PublisherAPI->response()
> #3 /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Curl.php(242): ChapterThree\AppleNewsAPI\PublisherAPI->request()
> #4 /home/website/craft/plugins/applenews/services/AppleNews_ApiService.php(153): ChapterThree\AppleNewsAPI\PublisherAPI->post()
> #5 /home/website/craft/plugins/applenews/services/AppleNews_ApiService.php(103): Craft\AppleNews_ApiService->post()
> #6 /home/website/craft/plugins/applenews/services/AppleNewsService.php(339): Craft\AppleNews_ApiService->updateArticle()
> #7 /home/website/craft/plugins/applenews/tasks/AppleNews_PostQueuedArticlesTask.php(90): Craft\AppleNewsService->postArticle()
> #8 /home/website/craft/app/services/TasksService.php(239): Craft\AppleNews_PostQueuedArticlesTask->runStep()
> #9 /home/website/craft/app/services/TasksService.php(200): Craft\TasksService->runTask()
> #10 /home/website/craft/app/controllers/TasksController.php(63): Craft\TasksService->runPendingTasks()
> #11 /home/website/craft/app/framework/web/actions/CInlineAction.php(49): Craft\TasksController->actionRunPendingTasks()
> #12 /home/website/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
> #13 /home/website/craft/app/framework/web/CController.php(286): Craft\TasksController->runAction()
> #14 /home/website/craft/app/framework/web/CController.php(265): Craft\TasksController->runActionWithFilters()
> #15 /home/website/craft/app/framework/web/CWebApplication.php(282): Craft\TasksController->run()
> #16 /home/website/craft/app/etc/web/WebApp.php(823): Craft\WebApp->runController()
> #17 /home/website/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
> #18 /home/website/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
> #19 /home/website/craft/app/index.php(62): Craft\WebApp->run()
> #20 /home/website/public_html/index.php(19): require_once()
> REQUEST_URI=/index.php/admin/actions/tasks/runPendingTasks
> 2017/11/29 10:08:51 [error] [application] Encountered an error running task 64229 (AppleNews_PostQueuedArticles), step 1 of 23: Array
> (
>     [code] => 404
>     [message] => HTTP/1.1 404 Not Found
>     [response] => stdClass Object
>         (
>             [errors] => Array
>                 (
>                     [0] => stdClass Object
>                         (
>                             [code] => NOT_FOUND
>                             [keyPath] => Array
>                                 (
>                                     [0] => articleId
>                                 )
> 
>                             [value] => 206516d9-4401-4b23-8338-5e5e8cf637fa
>                         )
> 
>                 )
> 
>         )
> 
> )
>  in /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197 on line 289 of /home/website/craft/plugins/applenews/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php

**Comment by bymayo** [comment]
I managed to get this working locally, but putting it on production produced this error. Which I'm unsure why.

**Comment by bymayo** [comment]
@brandonkelly Sorry to nudge you on this (I hate it when people do this to me!) But I've got my client on my back as to why this still isn't working :'(

**Comment by brandonkelly** [comment]
@bymayo That error is saying that your article ID is invalid. Have you double-checked that?

**Comment by jeremyfrank** [comment]
I'm having a similar issue with failed tasks and craft.log entries that look nearly identical to @bymayo's. Only difference is that my logs showed 22 total steps. After step 3 of 22, the log stops with the following error at the top:

```
Message Encountered an error running task 9 (AppleNews_PostQueuedArticles), step 3 of 22: Array
```

I did some digging around in the **craft_applenews_articles** table and found that the article referenced in step 3 DOES have a record with a status of LIVE, but it is not currently in Apple News (if you try to visit the shareUrl). In the **craft_applenews_articlequeue** table, that article is the first record in the table.

I'm wondering if deleting the above db records would allow the plugin to continue through the queue?

**Comment by jeremyfrank** [comment]
Additionally, the articles referenced in steps 1 and 2 show a status of PROCESSING in their db record, even though the shareURL value is good. Not sure if that means anything or not.

**Comment by brandonkelly** [comment]
If you update to version 1.0.2, the plugin will start logging which entry ID it’s about to publish, which should help track down issues.

**Comment by bymayo** [comment]
I don't know what happened but I'm no longer getting the articleID error!

One thing I did change though was I changed `autoPublishOnSave` setting to `false` so it doesn't auto publish, and they seem to go through okay now.

But obviously, it would be good to have this turned on.

One thing with this though, is it seems when it's set to true, that it tries to generate a shareUrl for ALL sections/channels, not just the ones your editing. Also, could this be conflicting with locales somehow?

**Comment by brandonkelly** [comment]
> I don't know what happened but I'm no longer getting the articleID error!

Weird, but glad it’s working now!

> With this though, is it seems when it's set to true, that it tries to generate a shareUrl for ALL sections/channels, not just the ones your editing. Also, could this be conflicting with locales somehow?

All that setting does is queues entries up to be published, each time they’re saved. The queuing process doesn’t take into account whether the entry _should_ be published – that will be determined at job execution time.

If you do something that causes all entries to be re-saved (e.g. update a section’s settings will trigger a re-save of all the entries in the section), then all of those entries will also be queued to be published to Apple News.
