### ISSUE TITLE
Does addFile not work with asset transforms?

### ISSUE THREAD

**Issue by jsunsawyer** [pixelandtonic/AppleNews#5]
When I download a News Preview where images use asset transforms, images are  no longer generated.

Without a transform, images are generated and display at the original size.

I've tried our normal S3 setup and a local file structure and have the same issue with both.

**Comment by brandonkelly** [comment]
The plugin currently doesn’t support image transforms. It should’t be necessary though, as Apple News will already apply its own transform to any images you supply, based on the size that’s needed for the device type.

**Comment by jsunsawyer** [comment]
Ah, bummer. The reason we wanted transforms to work was because our client would sometimes upload super wide or tall images and their blog tries to use a consistent aspect ratio for its images. I guess we'll just need to get them to pre-crop images for the blog. Helps create consistent hero images in Apple News as well, so maybe it'd be a good thing to have working at some point.

**Comment by brandonkelly** [comment]
You could manually transform an image before sending it to `addFile()`:

```php
$tempPath = craft()->path->getTempPath().StringHelper::randomString(10).'.'.$asset->getExtension();
$image = craft()->images->loadImage($asset->getTransformSource());
    ->scaleAndCrop(600, 400, false)
    ->saveAs($tempPath);
$url = $this->addFile($tempPath);
```
