### ISSUE TITLE
Craft 3?

### ISSUE THREAD

**Issue by codyjames** [pixelandtonic/AppleNews#8]
Will this get updated for Craft 3?

**Comment by brandonkelly** [comment]
Yes, but lower priority than finishing Commerce 2 / Commerce Lite.

**Comment by codyjames** [comment]
Alright. Thanks for the info.

**Comment by solivan** [comment]
@brandonkelly will the plug-in feature any additional features when it gets ported to Craft 3?

**Comment by codyjames** [comment]
It's been about a year on this. Any updates?

**Comment by khalwat** [comment]
Would love to see this get ported to Craft 3 as well.

**Comment by solivan** [comment]
This is a spot where I wish I had your level of knowledge @khalwat. I would love to contribute given just how much @brandonkelly and P&T as a whole has had on their hands as of late.

**Comment by khalwat** [comment]
I wish I had the time... I'd port it myself, but then @brandonkelly would just sigh and rewrite it :)

**Comment by john-henry** [comment]
I realize you had a lot on your plate with 3.2 but just checking in on progress or roadmap for this plugin?

We have a few clients who want to move from Craft 2 -> 3 and this plugin is quite important to them.

**Comment by stuntbox** [comment]
Speaking as one of those clients @john-henry mentioned (😛) is there an update on this? Apple News has become a major driver of visibility and traffic for those of us running editorial/news operations on Craft, and not having it available for v3 is a blocker for upgrading.

**Comment by brandonkelly** [comment]
Just released Apple News 2.0 with Craft 3 support! https://plugins.craftcms.com/apple-news

(Requires Craft 3.3 or later.)

**Comment by stuntbox** [comment]
Thanks, @brandonkelly!

**Comment by solivan** [comment]
I cannot thank you enough @brandonkelly, and not just for this but for all the hard work you and your team do. A most sincere thank you.
